Kotany-IF070-WebUI-RoR/NewVasjuky

- app/controllers/account/issues_controller.rb
- app/controllers/application_controller.rb
- app/models/issue.rb
- app/policies/issue_policy.rb
- app/views/account/issues/_issue.html.slim
- app/views/account/issues/index.html.slim
- app/views/devise/sessions/new.html.slim
- app/views/home/index.html.slim
- config/initializers/slim.rb
- config/routes.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/account_issues_controller_spec.rb
- spec/controllers/issues_controller_spec.rb
- Only admins and moderators can see list of all issues.
- Admins and moderators are able to approve or remove issues.
- Added controller Issues in account namespace
- Added rspecs for issues controller
Link to issue: https://github.com/Kotany-IF070-WebUI-RoR/NewVasjuky/issues/32
> Added approving and removing issues.

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/header.scss
- app/assets/stylesheets/home.scss
- app/assets/stylesheets/main.scss
- app/assets/stylesheets/variables_and_mixins.scss
- app/models/user.rb
- app/views/home/index.html.slim
- app/views/layouts/_head.html.slim
- app/views/layouts/_header.html.slim
- app/views/layouts/_logged_content.html.slim
- config/initializers/devise.rb
- db/migrate/20161228184415_add_image_url_to_users.rb
- db/migrate/20161228201601_remove_name_from_users.rb
- db/migrate/20161228201733_add_full_name_to_users.rb
- db/schema.rb
- spec/controllers/omniauth_callbacks_controller_spec.rb
- spec/factories/factories.rb
- Created header.
- Added temporary styles for it. (We will change it, when we implement new template, after first demo)
- Added image_url view in User model, for storing avatar from facebook.
link to issue: https://github.com/Kotany-IF070-WebUI-RoR/NewVasjuky/issues/26
> Creating header

- app/assets/javascripts/application.js
- app/assets/javascripts/flash.js
- app/assets/stylesheets/main.scss
- app/views/layouts/application.html.slim
Some minor bug fixes for flash messages:
* Removed old flash css classes
* Flash div moved into main row and got absolute positioning to avoid content jumping
* Added autofade
* Added flash message close on click
> Fixed flash message

- .gitignore
- .rubocop.yml
- spec/controllers/account/admin/admin_issues_controller_spec.rb
- spec/controllers/account/admin/admin_users_controller_spec.rb
- spec/controllers/issues_controller_spec.rb
- spec/controllers/omniauth_callbacks_controller_spec.rb
- spec/factories/factories.rb
- spec/models/issue_spec.rb
- spec/rails_helper.rb
- fixed rspec code style for passing rubocop checking
link to issue : https://github.com/Kotany-IF070-WebUI-RoR/NewVasjuky/issues/76
> fixed rspec code style for passing rubocop checking

- app/controllers/home_controller.rb
- app/controllers/issues_controller.rb
- app/models/issue.rb
- app/views/home/index.html.slim
- db/seeds.rb
In Misha's commit was old "approved" field, not implemented today status. This PR fixes it and also adds access to the "issues" page for non-registered users
> Minor fixes approve field

- app/assets/javascripts/comments.js
- app/controllers/comments_controller.rb
- app/controllers/issues_controller.rb
- app/helpers/comments_helper.rb
- app/models/comment.rb
- app/views/comments/_comments.html.slim
- app/views/comments/_comments_list.html.slim
Improvements:
- refreshing comments list after removing comments.
Bugs fixed:
- show action for issue when user isn't logged in.
- updating comments list when pagination page !== 1
> Bugs fixes and improvements

- app/assets/stylesheets/header.scss
- app/controllers/account/admin/users_controller.rb
- app/controllers/application_controller.rb
- app/controllers/home_controller.rb
- app/controllers/issues_controller.rb
- app/uploaders/attachment_uploader.rb
- app/views/comments/_comment.html.slim
- app/views/comments/_comments.html.slim
- app/views/layouts/_logged_content.html.slim
- spec/controllers/account/admin/admin_users_controller_spec.rb
- spec/controllers/comments_controller_spec.rb
- spec/controllers/issues/comments_controller_spec.rb
Issue https://github.com/Kotany-IF070-WebUI-RoR/NewVasjuky/issues/44
- Banned reporter can be logged in with some restriction of rights. He can't:
- add new issue
- comment issues (but he can view issues feed, single issue page and comments on it)
- delete his previously written comments
- If reporter is banned, warning-block appears in header. It contains a message about blocking, and it is shown on all pages.
- Added tests. Some other code improvements.
> Correct banning

- Gemfile
- Gemfile.lock
- app/controllers/comments_controller.rb
- app/controllers/issues/socializations_controller.rb
- app/controllers/issues_controller.rb
- app/models/follow.rb
- app/models/issue.rb
- app/models/user.rb
- app/views/issues/followees.html.slim
- app/views/issues/show.html.slim
- app/views/layouts/_logged_content.html.slim
- app/views/shared/_follow_link.html.slim
- config/routes.rb
- db/migrate/20170121122709_create_follows.rb
- db/migrate/20170121132522_add_followers_count_to_issue.rb
- db/migrate/20170121132658_add_followees_count_to_user.rb
- db/schema.rb
- spec/controllers/issues/comments_controller_spec.rb
- spec/controllers/issues/socializations_controller_spec.rb
- spec/models/issue_spec.rb
- spec/rails_helper.rb
- added following feature with socializations gem.
- added followees page with table of issues that user follows.
- added 'Follow/unfollow' button to issue view.
- user starts following when he comment issue.
> 49 adding follow feature

- app/models/issue.rb
- db/schema.rb
Fixes error with image link for facebook
> Fix attachment

- Gemfile
- Gemfile.lock
- app/controllers/account/admin/issues_controller.rb
- app/controllers/issues_controller.rb
- app/models/category.rb
- app/views/account/admin/issues/_issue.html.slim
- app/views/account/admin/issues/edit.html.slim
- app/views/issues/new.html.slim
- app/views/issues/show.html.slim
- app/views/layouts/application.html.slim
- config/initializers/any_login.rb
- config/locales/uk.yml
- db/seeds.rb
- add any_login gem
- in seeds added admin user (id: 1)
- minor bug fixes
> Added any_login gem; numerous minor bug fixes

- Procfile
- app/assets/stylesheets/header.scss
- app/controllers/comments_controller.rb
- app/controllers/issues_controller.rb
- app/helpers/application_helper.rb
- app/models/comment.rb
- app/models/user.rb
- app/views/account/admin/users/_bann_user.html.slim
- app/views/comments/_comment.html.slim
- app/views/comments/_comments.html.slim
- app/views/issue_mailer/issue_created.html.slim
- app/views/issues/show.html.slim
- app/views/layouts/_header.html.slim
- app/views/layouts/_logged_content.html.slim
- app/views/static_pages/home.html.slim
- config/routes.rb
- spec/mailers/previews/issue_mailer_preview.rb
Issue https://github.com/Kotany-IF070-WebUI-RoR/NewVasjuky/issues/114
- Added page for resolved problems;
- Fixes for Resque in production environment;
- Some visual fixes and code improvements.
**UPDATE:**
- Action `index` in `IssueController` is used for both open and closed issue feeds. Params protected from using invalid status values (only "open" and "closed" allowed).
- Added `active?` method in user model. It is used for checking if user is NOT banned.
- Some code improvements.
> Closed issues

- app/views/account/admin/issues/edit.html.slim
- app/views/issues/new.html.slim
Small addition to implement address autocomplete in Add new and Edit issue forms
> Added autocomplete

- app/assets/javascripts/leaflet-google.js
- app/assets/stylesheets/issues.scss
- app/views/account/admin/issues/edit.html.slim
- app/views/issues/map.html.slim
- app/views/issues/new.html.slim
- app/views/issues/show.html.slim
- app/views/shared/_head.html.slim
Implemented two-way binding between autocomplete and map.
Refactored map functionality for issues#new and issues#edit pages.
Removed google map script link from the global _head.
Fixed map styles for issue#show
> integreted map with autocomplete

- app/views/feeds/feed.html.slim
[BUGFIX] -when user does not have any events
> [BUGFIX] -when user does not have any events

- app/assets/javascripts/comments.js
- app/assets/stylesheets/issues.scss
- app/controllers/account/admin/issues_controller.rb
- app/controllers/issues_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/models/issue.rb
- app/models/user.rb
- app/views/account/admin/issues/_control_status_buttons.html.slim
- app/views/account/admin/issues/_issue.html.slim
- app/views/account/admin/issues/_issue_item.html.slim
- app/views/account/admin/issues/index.html.slim
- app/views/account/admin/issues/update.js.erb
- app/views/account/admin/users/_user.html.slim
- app/views/account/admin/users/update.js.erb
- app/views/issues/_issue.html.slim
- db/schema.rb
- spec/controllers/account/admin/admin_issues_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/mailers/issue_mailer_spec.rb
- Refactoring issues moderation page - now we can change status of issue via AJAX without page reload
- Removed ugly old buttons, added glyphicons
- Fixed sorting per user name
- Added specs for user rating
> Refactoring issues moderation page

- app/assets/stylesheets/main.scss
- app/views/issues/new.html.slim
- app/views/users/show.html.slim
- Make User Page view same as others in template
- Rearranged fields in Add new issue Form
- Changed z-index for fixed top menu to avoid overlap by Map layers
> Fixes for User Page view, Add New issue view, z-index for top menu

- app/assets/stylesheets/main.scss
- app/views/layouts/_footer.html.slim
- app/views/layouts/application.html.slim
Added Short description with copyright and sitemap on Footer (see screenshot)
> Added some info in Footer

- app/views/feeds/feed.html.slim
> [BUGFIX] - load events in users feed when user does not have any notifications

- app/assets/stylesheets/issues.scss
- app/mailers/issue_mailer.rb
- app/models/issue.rb
- app/views/account/admin/issues/_issue_item.html.slim
- app/views/common_pages/_home_feed.html.slim
- app/views/common_pages/home.html.slim
- app/views/issues/_breadcrumbs_show.html.slim
- app/views/issues/_issues_carousel.html.slim
- app/views/issues/show.html.slim
- spec/mailers/issue_mailer_spec.rb
Some fixes for responsive layouts and mailer.
> Responsive hot fix

- app/mailers/issue_mailer.rb
- app/views/issues/_issues_carousel.html.slim
- spec/mailers/issue_mailer_spec.rb
Fixed mailing to followers on issues status change.
> mailer bug fix

- app/models/issue.rb
- app/views/issues/_issues_carousel.html.slim
> Hot fix for carousel

- app/assets/javascripts/users.js
- app/controllers/account/admin/users_controller.rb
- app/controllers/application_controller.rb
- app/helpers/application_helper.rb
- app/views/account/admin/users/_ban_reason_form.html.slim
- app/views/account/admin/users/_bann_user.html.slim
- app/views/account/admin/users/_unban_form.html.slim
- app/views/account/admin/users/index.html.slim
- app/views/layouts/_header.html.slim
- app/views/layouts/application.html.slim
- app/views/users/show.html.slim
- db/migrate/20170223133708_add_ban_reason_to_user.rb
- db/schema.rb
- spec/controllers/account/admin/admin_users_controller_spec.rb
#164 
- When admin or moderator bans user, he sets the reason of ban
- Modal dialogs for ban and unban
- Reason of ban added to information messages for banned user
> Adds ability to mention the reason of ban

- app/views/account/admin/categories/new.html.slim
- public/404.html
- public/422.html
- public/500.html
Move back the quotes in `app/views/account/admin/categories/new.html.slim `
Error pages translated to Ukrainian
> [BUGFIX] Fix error when creating category

- app/views/account/admin/categories/edit.html.slim
> [BUGFIX] Fixed category edit page error

- app/assets/stylesheets/categories.scss
> [BUGFIX] - infinity scroll

- app/views/events/_event_details.html.slim
[BUGFIX] -  Event detail image
>             [BUGFIX] -  Event detail image

- app/uploaders/event_uploader.rb
>             [BUGFIX] -  S3 storage
